name: CI_meson

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  meson-build:
    strategy:
      fail-fast: false
      matrix:
        platform:
        - { name: Linux GCC 12,   os: ubuntu-latest,  compiler: g++12,    cxx: "g++-12",      backend: "ninja", build: "linux-libstdc++"}
        - { name: Linux Clang 14, os: ubuntu-latest,  compiler: clang-14, cxx: "clang++-14", backend: "ninja", build: "linux-libc++"}
        - { name: Windows 64,     os: windows-latest, compiler: msvc,     cxx: "cl",         backend: "vs2022 --vsenv", build: "win64-vs2022"}
        - { name: MacOS,          os: macos-latest,   compiler: clang++,  cxx: "clang++",    backend: "ninja", build: "osx-libc++"}
        build-type:
        - release

    name: ${{matrix.platform.name}} ${{matrix.build-type}} ${{matrix.config.name}}
    runs-on: ${{matrix.platform.os}}
    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - run: pip install meson ninja

    - name: meson setup
      run: CXX=${{matrix.platform.cxx}} meson setup ${{matrix.platform.build}} --backend=${{matrix.platform.backend}} -Dbuildtype=${{matrix.build-type}} -Dprefix=`pwd`/../install

    - name: Build
      run: meson compile -C ${{matrix.platform.build}}

    - name: Install
      run: meson install -C ${{matrix.platform.build}}

    - name: Test single header
      run: meson test -C ${{matrix.platform.build}}
